create table if not exists public.project_payments (
  id bigint generated by default as identity primary key,
  project_slug text not null,
  stripe_session_id text not null unique,
  payment_link text,
  plan_name text,
  client_email text,
  amount_total integer,
  currency text,
  paid_at timestamptz not null default now(),
  raw_event jsonb
);

create index if not exists project_payments_project_slug_idx
  on public.project_payments (project_slug);
